services:
  smaen-back:
    image: r.daco.dev/5ym/smaen_back
    networks:
      - main_default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.seb.rule=Host(`smaen.doany.id`) && PathPrefix(`/api`)"
        - "traefik.http.routers.seb.tls.certresolver=myresolver"
        - "traefik.http.services.seb.loadbalancer.server.port=80"
  smaen-front:
    image: r.daco.dev/5ym/smaen_front
    networks:
      - main_default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sef.rule=Host(`smaen.doany.id`)"
        - "traefik.http.routers.sef.tls.certresolver=myresolver"
        - "traefik.http.services.sef.loadbalancer.server.port=3000"
networks:
  main_default:
    external: true
    name: main_default
