services:
  smaen:
    image: r.daco.dev/5ym/smaen
    volumes:
      - smaen-data:/app/data
    networks:
      - main_default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sef.rule=Host(`smaen.doany.id`)"
        - "traefik.http.routers.sef.tls.certresolver=myresolver"
        - "traefik.http.services.sef.loadbalancer.server.port=3000"
volumes:
  smaen-data:
networks:
  main_default:
    external: true
    name: main_default
